Revert "Merge pull request #72 from searxng/dependabot/pip/master/jinja2-3.0.0"
This reverts commit 9e9a1ac6c3bb520e6813eead47b74a81ea9793f0, reversing
changes made to 5b1f04fff091ce9b61cd6167993ab44a9b8874bf.

We can't upgrade to jinja2==3.0.0 until Sphinx 4.1.0 has been released [1][2]

ERROR: Cannot install -r /share/searx/requirements-dev.txt (line 11) and jinja2==3.0.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested jinja2==3.0.0
    sphinx 4.0.1 depends on Jinja2<3.0 and >=2.3

[1] https://github.com/sphinx-doc/sphinx/issues/9088#issuecomment-831020758
[2] https://github.com/sphinx-doc/sphinx/pull/9161

Signed-off-by: Markus Heiser <markus.heiser@darmarit.de>